import jet1 from '../assets/images/jet1.png';
import jet2 from '../assets/images/jet2.png';
import jet3 from '../assets/images/jet3.png';
import jet4 from '../assets/images/jet4.png';
import jet5 from '../assets/images/jet5.png';
import jet6 from '../assets/images/jet6.png';
import jet7 from '../assets/images/jet7.png';
import jetInterior from '../assets/images/jet_interior.png';

// Unique generated aircraft images
const jetG700     = '/jets/jet_g700.png';
const jetGlobal   = '/jets/jet_global7500.png';
const jetFalcon   = '/jets/jet_falcon10x.png';
const jetG650     = '/jets/jet_g650.png';
const jetPhenom   = '/jets/jet_phenom.png';
const jetInterior2 = '/jets/jet_interior2.png';

export const AIRCRAFT = [
  {
    id: 'g700',
    name: 'Gulfstream G700',
    manufacturer: 'Gulfstream',
    year: 2023,
    class: 'Ultra Long Range',
    range: '7,500 nm', rangeNum: 7500,
    pax: 19, speed: 'Mach 0.925', ceiling: '51,000 ft',
    engines: 'Rolls-Royce Pearl 700',
    image: jetG700, gallery: [jetG700, jetInterior2], rating: 4.9, reviewCount: 127,
    status: 'Available', tail: 'N700GX', seats: 19,
    charterRate: 12500, priceDisplay: '$75M', priceNum: 75000000,
    route: { from: 'LHR', fromCity: 'London', to: 'DXB', toCity: 'Dubai' },
    departure: 'Oct 24, 08:00 BST', flightTime: '6h 45m',
    costs: { base: 85000, taxes: 4250, extras: 1200 },
    description: 'The Gulfstream G700 sets the standard for ultra-long-range travel. With the widest cabin in its class and unmatched range, it connects the world in absolute comfort.',
    features: ['Bespoke cabin design', 'Circadian lighting', 'Advanced noise suppression', 'Full galley with chef service', '100% fresh air cabin'],
  },
  {
    id: 'global7500',
    name: 'Bombardier Global 7500',
    manufacturer: 'Bombardier',
    year: 2022,
    class: 'Ultra Long Range',
    range: '7,700 nm', rangeNum: 7700,
    pax: 17, speed: 'Mach 0.925', ceiling: '51,000 ft',
    engines: 'GE Passport',
    image: jetGlobal, gallery: [jetGlobal, jetInterior], rating: 4.8, reviewCount: 98,
    status: 'Available', tail: 'N890BF', seats: 14,
    charterRate: 11200, priceDisplay: '$73M', priceNum: 73000000,
    route: { from: 'LHR', fromCity: 'London', to: 'DXB', toCity: 'Dubai' },
    departure: 'Oct 25, 10:00 BST', flightTime: '6h 45m',
    costs: { base: 75000, taxes: 3800, extras: 1200 },
    description: 'The Global 7500 features four distinct living spaces and the industry\'s only full-size kitchen, delivering a true home-in-the-sky experience across any distance.',
    features: ['Four living spaces', 'Full-size kitchen', 'Master suite', 'Smooth Flex Wing', 'Ka-band connectivity'],
  },
  {
    id: 'falcon10x',
    name: 'Dassault Falcon 10X',
    manufacturer: 'Dassault',
    year: 2023,
    class: 'Ultra Long Range',
    range: '7,500 nm', rangeNum: 7500,
    pax: 16, speed: 'Mach 0.925', ceiling: '51,000 ft',
    engines: 'Rolls-Royce Pearl 10X',
    image: jetFalcon, gallery: [jetFalcon, jetInterior2], rating: 4.7, reviewCount: 64,
    status: 'Available', tail: 'F-HWXY', seats: 16,
    charterRate: 10800, priceDisplay: '$80M', priceNum: 80000000,
    route: { from: 'CDG', fromCity: 'Paris', to: 'JFK', toCity: 'New York' },
    departure: 'Nov 02, 09:30 CET', flightTime: '7h 20m',
    costs: { base: 72000, taxes: 3600, extras: 1000 },
    description: 'Dassault\'s masterpiece combines French elegance with aerospace precision. The Falcon 10X offers the largest cabin cross-section of any purpose-built business jet.',
    features: ['Largest cabin cross-section', 'Panoramic windows', 'Low cabin altitude (4,000 ft)', 'Advanced fly-by-wire', 'Modular interior'],
  },
  {
    id: 'g650er',
    name: 'Gulfstream G650ER',
    manufacturer: 'Gulfstream',
    year: 2021,
    class: 'Ultra Long Range',
    range: '7,500 nm', rangeNum: 7500,
    pax: 18, speed: 'Mach 0.925', ceiling: '51,000 ft',
    engines: 'Rolls-Royce BR725',
    image: jetG650, gallery: [jetG650, jetInterior], rating: 4.8, reviewCount: 156,
    status: 'Available', tail: 'N650GX', seats: 18,
    charterRate: 9800, priceDisplay: '$66M', priceNum: 66000000,
    route: { from: 'JFK', fromCity: 'New York', to: 'SIN', toCity: 'Singapore' },
    departure: 'Nov 10, 22:00 EST', flightTime: '18h 45m',
    costs: { base: 66000, taxes: 3300, extras: 900 },
    description: 'The G650ER extended-range variant of the legendary G650 connects virtually any two cities non-stop with unrivalled speed and cabin comfort.',
    features: ['Extended range tank', 'Tri-zone cabin', 'Gulfstream Cabin Experience', 'GSA 8000 avionics', 'Lowest cabin noise'],
  },
  {
    id: 'falcon8x',
    name: 'Dassault Falcon 8X',
    manufacturer: 'Dassault',
    year: 2020,
    class: 'Long Range',
    range: '6,450 nm', rangeNum: 6450,
    pax: 16, speed: 'Mach 0.90', ceiling: '51,000 ft',
    engines: 'Pratt & Whitney PW307D',
    image: jet3, gallery: [jet3, jetInterior2], rating: 4.6, reviewCount: 82,
    status: 'Available', tail: 'F-HBLX', seats: 16,
    charterRate: 8500, priceDisplay: '$58M', priceNum: 58000000,
    route: { from: 'CDG', fromCity: 'Paris', to: 'HKG', toCity: 'Hong Kong' },
    departure: 'Nov 15, 07:00 CET', flightTime: '11h 30m',
    costs: { base: 57000, taxes: 2850, extras: 800 },
    description: 'The Falcon 8X is the ultimate expression of Dassault\'s tri-engine philosophy — combining range, altitude performance, and the widest cabin in its segment.',
    features: ['Trijet safety redundancy', 'EasyFit modular interior', 'FalconEye HUD', 'Short-field capability', 'Whisper-quiet cabin'],
  },
  {
    id: 'challenger850',
    name: 'Bombardier Challenger 850',
    manufacturer: 'Bombardier',
    year: 2019,
    class: 'Long Range',
    range: '4,994 nm', rangeNum: 4994,
    pax: 14, speed: 'Mach 0.82', ceiling: '41,000 ft',
    engines: 'General Electric CF34-3B',
    image: jet4, gallery: [jet4, jetInterior], rating: 4.4, reviewCount: 45,
    status: 'Charter Only', tail: 'C-GBOM', seats: 14,
    charterRate: 7200, priceDisplay: '$28M', priceNum: 28000000,
    route: { from: 'YYZ', fromCity: 'Toronto', to: 'LHR', toCity: 'London' },
    departure: 'Nov 20, 23:00 EST', flightTime: '7h 10m',
    costs: { base: 48000, taxes: 2400, extras: 600 },
    description: 'The Challenger 850 offers a stand-up cabin with exceptional comfort for transatlantic routes, featuring airline-style seating adapted for premium business travel.',
    features: ['Stand-up cabin', 'Aft lavatory', 'Galley with microwave', 'High-speed Ka-band', 'Quiet cabin'],
  },
  {
    id: 'legacy600',
    name: 'Embraer Legacy 600',
    manufacturer: 'Embraer',
    year: 2018,
    class: 'Large Cabin',
    range: '3,450 nm', rangeNum: 3450,
    pax: 13, speed: 'Mach 0.80', ceiling: '41,000 ft',
    engines: 'Rolls-Royce AE 3007A2',
    image: jet6, gallery: [jet6, jetInterior2], rating: 4.3, reviewCount: 38,
    status: 'Available', tail: 'PP-LEG', seats: 13,
    charterRate: 5800, priceDisplay: '$22M', priceNum: 22000000,
    route: { from: 'GRU', fromCity: 'São Paulo', to: 'MIA', toCity: 'Miami' },
    departure: 'Dec 01, 06:30 BRT', flightTime: '8h 00m',
    costs: { base: 39000, taxes: 1950, extras: 500 },
    description: 'The Legacy 600 combines Embraer\'s Brazilian engineering with exceptional range and a fully flat-bed configuration, perfect for transcontinental executive travel.',
    features: ['Flat-bed seats', 'Three-zone cabin', 'Full galley', 'Enclosed lavatory', 'High-altitude airports capability'],
  },
  {
    id: 'longitude',
    name: 'Citation Longitude',
    manufacturer: 'Cessna',
    year: 2022,
    class: 'Super Mid-Size',
    range: '3,500 nm', rangeNum: 3500,
    pax: 12, speed: 'Mach 0.84', ceiling: '47,000 ft',
    engines: 'Honeywell HTF7700L',
    image: jet1, gallery: [jet1, jetInterior], rating: 4.5, reviewCount: 71,
    status: 'Available', tail: 'N525CL', seats: 12,
    charterRate: 4500, priceDisplay: '$27M', priceNum: 27000000,
    route: { from: 'KLAS', fromCity: 'Las Vegas', to: 'KTEB', toCity: 'Teterboro' },
    departure: 'Dec 05, 14:00 PST', flightTime: '4h 45m',
    costs: { base: 30000, taxes: 1500, extras: 400 },
    description: 'The Citation Longitude redefines super-mid travel with a stand-up cabin, whisper-quiet Honeywell engines, and the longest range in its category.',
    features: ['Stand-up cabin', 'Lay-flat seats (optional)', 'ProLine Fusion avionics', 'Ergonomic seating', 'Quiet cabin tech'],
  },
  {
    id: 'phenom300e',
    name: 'Embraer Phenom 300E',
    manufacturer: 'Embraer',
    year: 2023,
    class: 'Light Jet',
    range: '2,010 nm', rangeNum: 2010,
    pax: 9, speed: 'Mach 0.80', ceiling: '45,000 ft',
    engines: 'Pratt & Whitney PW535E1',
    image: jetPhenom, gallery: [jetPhenom, jetInterior2], rating: 4.7, reviewCount: 113,
    status: 'Available', tail: 'N300EM', seats: 9,
    charterRate: 2800, priceDisplay: '$10.6M', priceNum: 10600000,
    route: { from: 'KORD', fromCity: 'Chicago', to: 'KMIA', toCity: 'Miami' },
    departure: 'Dec 08, 09:00 CST', flightTime: '2h 45m',
    costs: { base: 18000, taxes: 900, extras: 300 },
    description: 'The world\'s best-selling light jet, the Phenom 300E offers a remarkably spacious cabin and best-in-class performance that punches well above its category.',
    features: ['Best-in-class range', 'Largest cabin in segment', 'Autothrottle system', 'Electric seats', 'Baggage with external access'],
  },
  {
    id: 'pc24',
    name: 'Pilatus PC-24',
    manufacturer: 'Pilatus',
    year: 2021,
    class: 'Light Jet',
    range: '2,000 nm', rangeNum: 2000,
    pax: 9, speed: 'Mach 0.72', ceiling: '45,000 ft',
    engines: 'Williams FJ44-4A',
    image: jet7, gallery: [jet7, jetInterior], rating: 4.2, reviewCount: 29,
    status: 'Charter Only', tail: 'HB-VQQ', seats: 9,
    charterRate: 2600, priceDisplay: '$10.9M', priceNum: 10900000,
    route: { from: 'ZRH', fromCity: 'Zurich', to: 'NCE', toCity: 'Nice' },
    departure: 'Dec 12, 11:00 CET', flightTime: '1h 20m',
    costs: { base: 17000, taxes: 850, extras: 250 },
    description: 'The PC-24 is the world\'s only super-versatile jet — capable of operating from short, unpaved strips while delivering full business jet performance and comfort.',
    features: ['Gravel runway capable', 'Rear cargo door', 'Multi-mission flexibility', 'ACE avionics', 'Flat floor cabin'],
  },
];

export const getAircraftById = id => AIRCRAFT.find(a => a.id === id);
